basePath: /api
definitions:
  controllers.LoginDTO:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.LoginSuccessMessage:
    properties:
      token:
        type: string
    type: object
  controllers.RegisterDTO:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.RegisterSuccessMessage:
    properties:
      message:
        default: registration success
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Inheritence Management
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: User Info
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginSuccessMessage'
      summary: login
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: register new user
      parameters:
      - description: User Info
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RegisterSuccessMessage'
      summary: register user
      tags:
      - auth
  /api/user:
    get:
      description: get user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - Bearer: []
      summary: user
      tags:
      - user
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
